"use client";

import { useCallback, useEffect, useMemo, useRef } from "react";
import { useChat } from "@ai-sdk/react";
import type { FileUIPart, UIMessage } from "ai";
import { activeRunFor, useAppStore } from "@/lib/app-store";
import {
  BackgroundChatTransport,
  type AttachTarget,
} from "@/lib/chat-transport";
import type { ChatRunSummary } from "@/lib/types";

/* ------------------------------------------------------------------ */
/*  Chat controller                                                    */
/*                                                                     */
/*  Replies are generated by the server-side run engine                */
/*  (lib/chat-runs.ts), NOT by this tab: this hook only ATTACHES to a   */
/*  run over SSE to show it live. That gives:                           */
/*    • closing the tab no longer stops generation                      */
/*    • coming back re-attaches — the partial reply streams in          */
/*    • switching conversations / opening another tab still tracks it   */
/* ------------------------------------------------------------------ */

const RUN_POLL_MS = 3000;

/** The bits of the useChat instance the attach/poll logic needs. */
type ChatApi = {
  status: "ready" | "submitted" | "streaming" | "error";
  messages: UIMessage[];
  setMessages: (messages: UIMessage[] | ((m: UIMessage[]) => UIMessage[])) => void;
};

export function useChatController() {
  const settings = useAppStore((s) => s.settings);
  const activeConversationId = useAppStore((s) => s.activeConversationId);
  const setActiveConversation = useAppStore((s) => s.setActiveConversation);
  const loadConversations = useAppStore((s) => s.loadConversations);
  const loadArtifacts = useAppStore((s) => s.loadArtifacts);

  // Keep latest values available to stable callbacks.
  const cidRef = useRef<string | null>(activeConversationId);
  const settingsRef = useRef(settings);
  const loadConversationsRef = useRef(loadConversations);
  const loadArtifactsRef = useRef(loadArtifacts);
  const setActiveConversationRef = useRef(setActiveConversation);

  // The server-side run this client is currently watching.
  const attachRef = useRef<AttachTarget | null>(null);
  const attachingRef = useRef(false);
  // True when the last poll saw a live run for the active conversation, so we
  // can reconcile the transcript/artifacts once it finishes.
  const sawRunRef = useRef(false);
  const bootstrappedRef = useRef(false);
  // Latest controller internals for the background poll loop (which must not
  // resubscribe on every render).
  const apiRef = useRef<{
    chat: ChatApi;
    attachToRun: (runId: string) => Promise<boolean>;
    syncConversation: (cid: string) => Promise<void>;
    reloadStored: (cid: string) => Promise<UIMessage[] | null>;
    refreshRuns: () => Promise<ChatRunSummary[]>;
  } | null>(null);

  useEffect(() => {
    cidRef.current = activeConversationId;
    settingsRef.current = settings;
    loadConversationsRef.current = loadConversations;
    loadArtifactsRef.current = loadArtifacts;
    setActiveConversationRef.current = setActiveConversation;
  });

  // The conversation id is allocated up-front (on the first send) rather than
  // when the reply finishes, so artifacts/agents created mid-reply are tied to
  // it and keep showing up in that conversation's artifact list.
  const ensureConversationId = useCallback((): string => {
    if (!cidRef.current) {
      cidRef.current =
        typeof crypto !== "undefined" && "randomUUID" in crypto
          ? crypto.randomUUID()
          : `conv-${Date.now()}`;
      setActiveConversationRef.current(cidRef.current);
    }
    return cidRef.current;
  }, []);

  /* ------------------------- run bookkeeping ------------------------- */

  const fetchRuns = useCallback(async (): Promise<ChatRunSummary[]> => {
    try {
      const res = await fetch("/api/chat/runs", { cache: "no-store" });
      if (!res.ok) return [];
      const data = await res.json();
      return Array.isArray(data?.runs) ? (data.runs as ChatRunSummary[]) : [];
    } catch {
      return [];
    }
  }, []);

  const refreshRuns = useCallback(async (): Promise<ChatRunSummary[]> => {
    const runs = await fetchRuns();
    useAppStore.getState().setRuns(runs);
    return runs;
  }, [fetchRuns]);

  const reloadStored = useCallback(
    async (cid: string): Promise<UIMessage[] | null> => {
      try {
        const res = await fetch(`/api/conversations/${cid}`, { cache: "no-store" });
        if (!res.ok) return null;
        const conv = await res.json();
        return Array.isArray(conv.messages) ? (conv.messages as UIMessage[]) : [];
      } catch {
        return null;
      }
    },
    [],
  );

  // The run engine transport: sends to /api/chat (which starts a background
  // run) and resumes from /api/chat/runs/:id/events.
  //
  // The compiler's ref rule can't tell that these callbacks only read refs when
  // a request is actually made (never during render), and it can't preserve a
  // manual useMemo whose closures read refs — both are fine here.
  /* eslint-disable react-hooks/refs, react-hooks/preserve-manual-memoization -- deferred request callbacks read the attach ref lazily */
  const transport = useMemo(
    () =>
      new BackgroundChatTransport({
        getAttachTarget: () => attachRef.current,
        onRunStarted: (runId) => {
          attachRef.current = { runId };
          void refreshRuns();
        },
      }),
    [refreshRuns],
  );
  /* eslint-enable react-hooks/refs, react-hooks/preserve-manual-memoization */

  const chat = useChat({
    transport,
    onFinish: async () => {
      // The server already persisted the transcript (that is the whole point of
      // the run engine) — this just refreshes what the UI shows.
      try {
        const cid = cidRef.current;
        await loadConversationsRef.current();
        if (cid) await loadArtifactsRef.current(cid);
        await refreshRuns();
      } catch {
        /* best-effort */
      }
    },
    onError: (e) => {
      console.error("[chat]", e?.message || e);
    },
  });

  /** Attach to a live run: load its snapshot, then stream it live. */
  const attachToRun = useCallback(
    async (runId: string): Promise<boolean> => {
      if (attachingRef.current) return false;
      attachingRef.current = true;
      try {
        const res = await fetch(`/api/chat/runs/${runId}`, { cache: "no-store" });
        if (!res.ok) {
          if (attachRef.current?.runId === runId) attachRef.current = null;
          return false;
        }
        const snap = await res.json();
        const messages: UIMessage[] = Array.isArray(snap?.messages)
          ? snap.messages
          : [];
        const run = snap?.run as ChatRunSummary | undefined;

        attachRef.current = { runId };
        if (run?.conversationId) {
          cidRef.current = run.conversationId;
          setActiveConversationRef.current(run.conversationId);
        }
        chat.setMessages(messages);
        chat.clearError();
        sawRunRef.current = run?.status === "running";
        // A finished run (or one whose chunk log was trimmed) is already fully
        // in `messages` — there is nothing to stream.
        if (run?.status === "running" && run.replayable !== false) {
          await chat.resumeStream();
        }
        return true;
      } catch {
        return false;
      } finally {
        attachingRef.current = false;
      }
    },
    [chat],
  );

  /** Show the stored transcript of a conversation, attaching to a live run. */
  const syncConversation = useCallback(
    async (cid: string) => {
      const busy = chat.status === "submitted" || chat.status === "streaming";
      if (busy && attachRef.current?.runId) return; // don't clobber our own stream

      const runs = await fetchRuns();
      useAppStore.getState().setRuns(runs);
      const live = runs.find(
        (r) => r.conversationId === cid && r.status === "running",
      );
      if (live) {
        await attachToRun(live.id);
        return;
      }
      attachRef.current = null;
      const messages = await reloadStored(cid);
      if (messages) {
        chat.setMessages(messages);
        chat.clearError();
      }
      void loadArtifactsRef.current(cid);
    },
    [attachToRun, chat, fetchRuns, reloadStored],
  );

  /* -------------------------- chat operations -------------------------- */

  /** Stop watching a run without stopping it on the server. */
  const detach = useCallback(async () => {
    attachRef.current = null;
    try {
      await chat.stop();
    } catch {
      /* ignore */
    }
  }, [chat]);

  /** Start a fresh chat (empty message list). */
  const startNew = useCallback(() => {
    void detach();
    chat.setMessages([]);
    chat.clearError();
    cidRef.current = null;
    setActiveConversationRef.current(null);
  }, [chat, detach]);

  /** Load an existing conversation's messages (and any live run on it). */
  const openConversation = useCallback(
    async (id: string) => {
      if (chat.status === "submitted" || chat.status === "streaming") {
        await detach();
      }
      cidRef.current = id;
      setActiveConversationRef.current(id);
      attachRef.current = null;
      await syncConversation(id);
    },
    [chat.status, detach, syncConversation],
  );

  /** Send a user message (with optional file parts) using current settings. */
  const send = useCallback(
    (text: string, files?: FileUIPart[]) => {
      const cid = ensureConversationId();
      // Already generating for this conversation? Watch that run instead of
      // starting a second one (the server rejects it with a 409 anyway).
      const live = activeRunFor(useAppStore.getState().runs, cid);
      if (live) {
        void attachToRun(live.id);
        return;
      }
      const payload: { text: string; files?: FileUIPart[] } = { text };
      if (files?.length) payload.files = files;
      void chat.sendMessage(payload, {
        body: { settings: settingsRef.current, conversationId: cid },
      });
    },
    [attachToRun, chat, ensureConversationId],
  );

  const regenerate = useCallback(() => {
    const cid = ensureConversationId();
    const live = activeRunFor(useAppStore.getState().runs, cid);
    if (live) {
      void attachToRun(live.id);
      return;
    }
    void chat.regenerate({
      body: { settings: settingsRef.current, conversationId: cid },
    });
  }, [attachToRun, chat, ensureConversationId]);

  /** Stop generating — aborts the run server-side and keeps the partial reply. */
  const stop = useCallback(() => {
    const runId = attachRef.current?.runId;
    void detach();
    if (runId) {
      void fetch(`/api/chat/runs/${runId}`, { method: "DELETE" }).catch(() => {});
    }
    // Give the server a moment to finalize the partial reply, then refresh.
    setTimeout(() => {
      void refreshRuns();
      void loadConversationsRef.current();
      const cid = cidRef.current;
      if (cid) void loadArtifactsRef.current(cid);
    }, 700);
  }, [detach, refreshRuns]);

  /** Stop a run we are not watching (used by the background-run banner). */
  const stopRun = useCallback(
    async (runId: string) => {
      await fetch(`/api/chat/runs/${runId}`, { method: "DELETE" }).catch(() => {});
      await refreshRuns();
      await loadConversationsRef.current();
      const cid = cidRef.current;
      if (!cid) return;
      void loadArtifactsRef.current(cid);
      if (chat.status === "submitted" || chat.status === "streaming") return;
      const messages = await reloadStored(cid);
      if (messages) chat.setMessages(messages);
    },
    [chat, refreshRuns, reloadStored],
  );

  /** Re-attach to a run by hand (banner "Show" button). */
  const showRun = useCallback(
    async (runId: string) => {
      await attachToRun(runId);
    },
    [attachToRun],
  );

  /* ----------------------------- lifecycle ----------------------------- */

  // Keep the poll loop's view of the controller fresh. It reads through this
  // ref so the interval doesn't have to resubscribe on every render.
  useEffect(() => {
    apiRef.current = {
      chat,
      attachToRun,
      syncConversation,
      reloadStored,
      refreshRuns,
    };
  });

  // Bootstrap on mount: restore the persisted conversation (the store keeps
  // activeConversationId) and attach to any run that is still generating —
  // this is what makes a returning user immediately see the live reply.
  useEffect(() => {
    if (bootstrappedRef.current) return;
    bootstrappedRef.current = true;
    const cid = cidRef.current;
    const api = apiRef.current;
    if (!api) return;
    if (cid) void api.syncConversation(cid);
    else void api.refreshRuns();
  }, []);

  // Poll for runs started elsewhere (another tab, a reload, or a run this
  // client detached from) and reconcile once they finish.
  useEffect(() => {
    let cancelled = false;
    let timer: ReturnType<typeof setTimeout>;

    const tick = async () => {
      try {
        const api = apiRef.current;
        if (!api) return;
        const runs = await api.refreshRuns();
        if (cancelled) return;

        const cid = cidRef.current;
        const live = cid
          ? runs.find(
              (r) => r.conversationId === cid && r.status === "running",
            ) ?? null
          : null;
        const attachedId = attachRef.current?.runId ?? null;
        const busy =
          api.chat.status === "submitted" || api.chat.status === "streaming";

        if (live && live.id !== attachedId && !busy && !attachingRef.current) {
          await api.attachToRun(live.id);
        } else if (!live && attachedId) {
          // The run we were watching disappeared (e.g. server restart).
          attachRef.current = null;
        }

        if (live) {
          sawRunRef.current = true;
        } else if (sawRunRef.current) {
          sawRunRef.current = false;
          void loadConversationsRef.current();
          if (cid) {
            void loadArtifactsRef.current(cid);
            if (!busy) {
              const messages = await api.reloadStored(cid);
              const localLast = api.chat.messages[api.chat.messages.length - 1];
              const serverLast = messages?.[messages.length - 1];
              // Only adopt the stored transcript when it is the same turn we
              // were showing — never clobber a newer local message.
              if (messages && !cancelled && (!localLast || serverLast?.id === localLast.id)) {
                api.chat.setMessages(messages);
              }
            }
          }
        }
      } catch {
        /* keep polling */
      } finally {
        if (!cancelled) timer = setTimeout(tick, RUN_POLL_MS);
      }
    };

    void tick();
    return () => {
      cancelled = true;
      clearTimeout(timer);
    };
  }, []);

  return {
    ...chat,
    settings,
    send,
    startNew,
    openConversation,
    regenerate,
    stop,
    activeConversationId,
    /* background runs */
    stopRun,
    showRun,
    attachToRun,
    refreshRuns,
  };
}

export type ChatController = ReturnType<typeof useChatController>;
